# Generated by Django 2.1.7 on 2019-08-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadPrice', models.IntegerField(default=0, verbose_name='Thread Price')),
                ('jobOfferPrice', models.IntegerField(default=0, verbose_name='Job Offer Price')),
                ('challengePrice', models.IntegerField(default=0, verbose_name='Challenge Price')),
                ('defaultMaxCoins', models.IntegerField(default=10, verbose_name='Default maximum coins')),
                ('directPurchaseCoinsPrice', models.FloatField(default=3, verbose_name='Coins price')),
            ],
        ),
    ]
