# Generated by Django 2.2.4 on 2019-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftable',
            name='biological',
            field=models.BooleanField(default=False, verbose_name='Biológico'),
        ),
        migrations.AddField(
            model_name='craftable',
            name='scientificCost',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste científico'),
        ),
        migrations.AddField(
            model_name='craftable',
            name='vehicular',
            field=models.BooleanField(default=False, verbose_name='Para coche'),
        ),
    ]
