# Generated by Django 2.1.7 on 2019-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Class name')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Spell name')),
                ('school', models.TextField(verbose_name='School of Magic')),
                ('level', models.PositiveIntegerField(verbose_name='Spell level')),
                ('verbalComponent', models.BooleanField(verbose_name='Verbal Component')),
                ('somaticComponent', models.BooleanField(verbose_name='Somatic Component')),
                ('materialComponent', models.BooleanField(verbose_name='Material Component')),
                ('materialRequirements', models.TextField(verbose_name='Material requirements')),
                ('castTime', models.TextField(verbose_name='Casting time')),
                ('duration', models.TextField(verbose_name='Duration')),
                ('range', models.TextField(verbose_name='Range/Area')),
                ('effect', models.TextField(verbose_name='Damage/effect type')),
                ('save', models.TextField(verbose_name='Attack or save')),
                ('description', models.TextField(verbose_name='Description')),
                ('classes', models.ManyToManyField(to='RolAndalucia.CharacterClass', verbose_name='Classes that use this spell')),
            ],
        ),
    ]
