# Generated by Django 2.1.7 on 2019-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0002_characterclass_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='materialRequirements',
            field=models.TextField(blank=True, verbose_name='Material requirements'),
        ),
    ]
