# Generated by Django 2.2.4 on 2019-11-29 17:31

import django.core.validators
from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0003_auto_20190904_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre de trabajo')),
                ('empleador', models.CharField(blank=True, max_length=400, verbose_name='Empleador')),
                ('salario', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Salario ofrecido')),
                ('descripcion', martor.models.MartorField(default='', verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre de personaje')),
                ('maxHp', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Salud máxima')),
                ('currentHp', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Salud actual')),
                ('habilidades', martor.models.MartorField(blank=True, default='', verbose_name='Habilidades')),
                ('photo', models.CharField(blank=True, max_length=400, verbose_name='Imagen')),
                ('clase', models.ManyToManyField(blank=True, null=True, to='RolAndalucia.CharacterClass', verbose_name='Clase principal')),
                ('hechizos', models.ManyToManyField(to='RolAndalucia.Spell', verbose_name='Hechizos')),
            ],
        ),
    ]
