# Generated by Django 2.1.7 on 2019-08-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0004_auto_20190819_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='attack_save',
            field=models.TextField(default='N/A', verbose_name='Attack or save'),
        ),
        migrations.AddField(
            model_name='spell',
            name='castTime',
            field=models.TextField(default='N/A', verbose_name='Casting time'),
        ),
        migrations.AddField(
            model_name='spell',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.TextField(default='N/A', verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='spell',
            name='effect',
            field=models.TextField(default='N/A', verbose_name='Damage/effect type'),
        ),
        migrations.AddField(
            model_name='spell',
            name='materialComponent',
            field=models.BooleanField(default=False, verbose_name='Material Component'),
        ),
        migrations.AddField(
            model_name='spell',
            name='materialRequirements',
            field=models.TextField(blank=True, verbose_name='Material requirements'),
        ),
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.TextField(default='N/A', verbose_name='Range/Area'),
        ),
        migrations.AddField(
            model_name='spell',
            name='somaticComponent',
            field=models.BooleanField(default=False, verbose_name='Somatic Component'),
        ),
        migrations.AddField(
            model_name='spell',
            name='verbalComponent',
            field=models.BooleanField(default=False, verbose_name='Verbal Component'),
        ),
    ]
