# Generated by Django 2.1.7 on 2019-08-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0005_auto_20190819_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='attack_save',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Attack or save'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='castTime',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Casting time'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='effect',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Damage/effect type'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='materialRequirements',
            field=models.CharField(blank=True, max_length=200, verbose_name='Material requirements'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Spell name'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Range/Area'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(max_length=30, verbose_name='School of Magic'),
        ),
    ]
