# Generated by Django 2.1.7 on 2019-08-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0006_auto_20190819_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craftable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de hechizo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('programmingCost', models.PositiveIntegerField(verbose_name='Coste de programación')),
                ('engineeringCost', models.PositiveIntegerField(verbose_name='Coste de ingeniería')),
                ('materialCost', models.TextField(verbose_name='Costes en materiales')),
                ('effect', models.TextField(verbose_name='Efectos')),
            ],
        ),
    ]
