# Generated by Django 2.1.7 on 2019-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0007_craftable'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='concentration',
            field=models.BooleanField(default=False, verbose_name='Concentration'),
        ),
    ]
