# Generated by Django 2.1.7 on 2019-08-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0008_spell_concentration'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftable',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='craftable',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre de creación'),
        ),
    ]
