# Generated by Django 2.1.7 on 2019-08-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0009_auto_20190819_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de objeto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('magic', models.BooleanField(default=False, verbose_name='Magia')),
                ('wearable', models.BooleanField(default=False, verbose_name='Equipable')),
                ('effects', models.TextField(blank=True, verbose_name='Efectos')),
                ('photo', models.URLField(blank=True, verbose_name='Imagen')),
            ],
        ),
        migrations.AddField(
            model_name='craftable',
            name='photo',
            field=models.URLField(blank=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='craftable',
            name='materialCost',
            field=models.TextField(blank=True, verbose_name='Costes en materiales'),
        ),
    ]
