# Generated by Django 2.1.7 on 2019-08-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0010_auto_20190820_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='', max_length=30, verbose_name='Tipo de objeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nombre de objeto'),
        ),
    ]
