# Generated by Django 2.2.4 on 2019-12-13 18:53

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0011_personaje_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='descripcion',
            field=martor.models.MartorField(blank=True, default='', verbose_name='Habilidades'),
        ),
    ]
