# Generated by Django 2.1.7 on 2019-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0011_auto_20190820_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='characteristics',
            field=models.TextField(blank=True, verbose_name='Características'),
        ),
    ]
