# Generated by Django 2.1.7 on 2019-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0012_item_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftable',
            name='engineeringCost',
            field=models.IntegerField(verbose_name='Coste de ingeniería'),
        ),
        migrations.AlterField(
            model_name='craftable',
            name='programmingCost',
            field=models.IntegerField(verbose_name='Coste de programación'),
        ),
    ]
