# Generated by Django 2.2.4 on 2019-12-20 19:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0013_auto_20191215_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='armorClass',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Clase de armadura'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='inspiration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaje',
            name='temporaryHp',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Salud máxima'),
        ),
        migrations.CreateModel(
            name='StatBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('dexterity', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('constitution', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('intelligence', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('wisdom', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('charisma', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('proficiencyBonus', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('statBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Personaje')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Nombre de objeto')),
                ('descripcion', martor.models.MartorField(null=True, verbose_name='Descripción')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Item')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Personaje')),
            ],
        ),
    ]
