# Generated by Django 2.1.7 on 2019-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0013_auto_20190820_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftable',
            name='engineeringCost',
            field=models.PositiveIntegerField(verbose_name='Coste de ingeniería'),
        ),
        migrations.AlterField(
            model_name='craftable',
            name='programmingCost',
            field=models.PositiveIntegerField(verbose_name='Coste de programación'),
        ),
    ]
