# Generated by Django 2.1.7 on 2019-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0014_auto_20190820_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rareza'),
        ),
        migrations.AlterField(
            model_name='item',
            name='characteristics',
            field=models.TextField(blank=True, help_text='Genera tablas en https://www.tablesgenerator.com/markdown_tables#', verbose_name='Características'),
        ),
    ]
