# Generated by Django 2.2.4 on 2019-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0015_auto_20191221_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
