# Generated by Django 2.2.4 on 2019-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0016_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftable',
            name='photo',
            field=models.CharField(blank=True, max_length=400, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.CharField(blank=True, max_length=400, verbose_name='Imagen'),
        ),
    ]
