# Generated by Django 2.2.4 on 2019-12-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0016_inventoryentry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
