# Generated by Django 2.2.4 on 2019-12-23 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0017_inventoryentry_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statblock',
            name='statBlock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statBlock', to='RolAndalucia.Personaje'),
        ),
    ]
