# Generated by Django 2.2.4 on 2019-08-27 17:40

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0017_auto_20190827_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='description',
            field=mdeditor.fields.MDTextField(default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.TextField(verbose_name='Nombre de clase'),
        ),
    ]
