# Generated by Django 2.2.4 on 2019-12-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0018_auto_20191223_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statblock',
            name='statBlock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Personaje'),
        ),
    ]
