# Generated by Django 2.2.4 on 2019-08-27 18:02

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0018_auto_20190827_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='description',
            field=martor.models.MartorField(default='', verbose_name='Descripción'),
        ),
    ]
