# Generated by Django 2.2.4 on 2019-08-27 18:14

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0019_auto_20190827_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('content', martor.models.MartorField(default='', verbose_name='Content')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
