# Generated by Django 2.2.4 on 2019-08-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0020_rule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.AddField(
            model_name='rule',
            name='parent_rule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Rule', verbose_name='Regla raíz'),
        ),
    ]
