# Generated by Django 2.2.4 on 2019-12-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0020_auto_20191223_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statblock',
            name='statBlock',
        ),
        migrations.AddField(
            model_name='personaje',
            name='statBlock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.StatBlock'),
        ),
    ]
