# Generated by Django 3.1 on 2020-08-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0022_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de habilidad')),
                ('descripcion', models.TextField(default='Esta habilidad no tiene descripción', verbose_name='Descripción')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('desbloqueo', models.TextField(verbose_name='Condiciones de desbloqueo')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='RolAndalucia.characterclass')),
                ('habilidadPadre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.ability')),
            ],
        ),
    ]
