# Generated by Django 2.2.4 on 2019-08-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0023_auto_20190827_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='parentRule',
            new_name='parent',
        ),
    ]
