# Generated by Django 2.2.4 on 2019-08-27 20:53

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0024_auto_20190827_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='parent',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='RolAndalucia.Rule'),
        ),
    ]
