# Generated by Django 3.1 on 2020-08-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0024_auto_20200813_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(choices=[('Abjuración', 'Abjuración'), ('Conjuración', 'Conjuración'), ('Adivinación', 'Adivinación'), ('Encantamiento', 'Encantamiento'), ('Evocación', 'Evocación'), ('Ilusión', 'Ilusión'), ('Nigromancia', 'Nigromancia'), ('Transmutación', 'Transmutación')], max_length=30, verbose_name='School of Magic'),
        ),
    ]
