# Generated by Django 2.2.4 on 2019-08-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0025_auto_20190827_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='order',
        ),
    ]
