# Generated by Django 3.1 on 2020-09-07 16:15

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0026_auto_20200815_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='desbloqueo',
            field=martor.models.MartorField(default='N/A', verbose_name='Condiciones de desbloqueo'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='descripcion',
            field=martor.models.MartorField(default='Esta habilidad no tiene descripción', verbose_name='Descripción'),
        ),
    ]
