# Generated by Django 2.2.4 on 2019-08-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0027_auto_20190827_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='parentId',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='ID de registro superior'),
        ),
    ]
