# Generated by Django 2.2 on 2021-08-10 07:21

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0027_auto_20200907_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=131072)),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=240, verbose_name='Destinatario')),
            ],
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDueno', models.CharField(max_length=60, verbose_name='Dueño')),
                ('modelo', models.CharField(max_length=60, verbose_name='Modelo')),
                ('fecha', models.DateTimeField()),
                ('colorAcento', colorfield.fields.ColorField(default='#5B7DB3', max_length=18)),
                ('calendarioJson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RolAndalucia.CalendarioJson')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=240, verbose_name='Titular')),
                ('subtitulo', models.CharField(max_length=240, verbose_name='Subítulo')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Movil')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeMovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mio', models.BooleanField()),
                ('texto', models.CharField(max_length=2048)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Conversacion')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowRes', models.CharField(max_length=240, verbose_name='Emisor')),
                ('hiRes', models.CharField(max_length=240, verbose_name='Asunto')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Movil')),
            ],
        ),
        migrations.CreateModel(
            name='CorreoMovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=240, verbose_name='Emisor')),
                ('asunto', models.CharField(max_length=240, verbose_name='Asunto')),
                ('cuerpo', models.CharField(max_length=2048, verbose_name='Cuerpo')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Movil')),
            ],
        ),
        migrations.AddField(
            model_name='conversacion',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.Movil'),
        ),
    ]
