# Generated by Django 2.2.4 on 2019-08-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0028_rule_parentid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={},
        ),
        migrations.RemoveField(
            model_name='rule',
            name='order',
        ),
    ]
