# Generated by Django 2.2 on 2021-08-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0029_auto_20210810_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversacions', to='RolAndalucia.Movil'),
        ),
        migrations.AlterField(
            model_name='correomovil',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correoMovils', to='RolAndalucia.Movil'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='RolAndalucia.Movil'),
        ),
        migrations.AlterField(
            model_name='mensajemovil',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajeMovils', to='RolAndalucia.Conversacion'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='RolAndalucia.Movil'),
        ),
    ]
