# Generated by Django 2.2 on 2021-08-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0030_auto_20210810_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('titulo', models.CharField(max_length=240, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=480, verbose_name='Subítulo')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='RolAndalucia.Movil')),
            ],
        ),
    ]
