# Generated by Django 2.2.4 on 2019-08-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0030_remove_rule_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
