# Generated by Django 2.2 on 2021-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0032_llamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correomovil',
            name='cuerpo',
            field=models.TextField(max_length=2048, verbose_name='Cuerpo'),
        ),
    ]
