# Generated by Django 2.2 on 2021-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0033_auto_20210811_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajemovil',
            name='texto',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='nota',
            name='subtitulo',
            field=models.TextField(max_length=480, verbose_name='Subítulo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.TextField(max_length=1024, verbose_name='Subítulo'),
        ),
    ]
