# Generated by Django 2.2.24 on 2021-09-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0035_foto_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PjMadrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de clase')),
                ('position', models.CharField(max_length=200, verbose_name='Nombre de clase')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TagPjMadrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de clase')),
                ('key', models.CharField(max_length=16, verbose_name='Nombre de clase')),
            ],
        ),
    ]
