# Generated by Django 2.2.24 on 2021-09-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0036_pjmadrid_tagpjmadrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjmadrid',
            name='tags',
            field=models.ManyToManyField(related_name='pjs', to='RolAndalucia.TagPjMadrid', verbose_name='Tags'),
        ),
    ]
