# Generated by Django 2.2.24 on 2021-09-09 14:47

from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0037_pjmadrid_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjmadrid',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pjmadrid',
            name='pic',
            field=models.ImageField(blank=True, storage=django_imgur.storage.ImgurStorage(), upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='pjmadrid',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Trabajo'),
        ),
        migrations.AlterField(
            model_name='tagpjmadrid',
            name='key',
            field=models.CharField(max_length=16, verbose_name='Valor de etiqueta'),
        ),
        migrations.AlterField(
            model_name='tagpjmadrid',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre de etiqueta'),
        ),
    ]
