# Generated by Django 2.2.24 on 2021-09-10 23:48

from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0038_auto_20210909_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjmadrid',
            name='jugador',
            field=models.CharField(max_length=30, null=True, verbose_name='Jugador'),
        ),
        migrations.AlterField(
            model_name='pjmadrid',
            name='pic',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='profile_pics'),
        ),
    ]
