# Generated by Django 2.2.24 on 2021-09-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0039_auto_20210911_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjmadrid',
            name='jugador',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Jugador'),
        ),
    ]
