# Generated by Django 2.2.24 on 2021-10-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0041_telegramchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='groupId',
            field=models.CharField(default=0, max_length=64, verbose_name='ID del grupo'),
            preserve_default=False,
        ),
    ]
