# Generated by Django 2.2.24 on 2021-10-24 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RolAndalucia', '0042_telegramchat_groupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DndAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('campaign', models.TextField(verbose_name='Campaña')),
                ('session_name', models.TextField(verbose_name='Nombre de sesión')),
                ('confirmed', models.BooleanField(verbose_name='Sesión confirmada')),
            ],
        ),
        migrations.CreateModel(
            name='DndRsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dndAppointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='RolAndalucia.DndAppointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
