# Generated by Django 2.2.24 on 2021-10-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0043_dndappointment_dndrsvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DndAppointmentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
            ],
        ),
        migrations.RemoveField(
            model_name='dndappointment',
            name='date',
        ),
        migrations.AlterField(
            model_name='dndrsvp',
            name='dndAppointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='RolAndalucia.DndAppointmentDate'),
        ),
        migrations.AddField(
            model_name='dndappointmentdate',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='RolAndalucia.DndAppointment'),
        ),
    ]
