# Generated by Django 2.2.24 on 2021-10-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0045_dndrsvp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndappointment',
            name='tipo',
            field=models.CharField(choices=[('P', 'presencial'), ('O', 'online')], default='O', max_length=2, verbose_name='Tipo de sesión'),
            preserve_default=False,
        ),
    ]
