# Generated by Django 2.2.24 on 2021-10-27 20:24

from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0046_dndappointment_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndappointment',
            name='pic',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='session_pics'),
        ),
    ]
