# Generated by Django 2.2.24 on 2021-10-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0047_dndappointment_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dndappointment',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='dndappointmentdate',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Fecha confirmada'),
            preserve_default=False,
        ),
    ]
