# Generated by Django 2.2.24 on 2021-10-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0049_dndappointment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndrsvp',
            name='type',
            field=models.CharField(choices=[('YES', 'Confirmo asistencia'), ('IF_NEED', 'Solo si es necesario')], max_length=30, verbose_name='Tipo de reserva'),
        ),
    ]
