# Generated by Django 2.2.24 on 2021-10-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0050_auto_20211028_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndappointment',
            name='chats',
            field=models.ManyToManyField(to='RolAndalucia.TelegramChat', verbose_name='Chats para anunciar'),
        ),
    ]
