# Generated by Django 2.2.24 on 2021-12-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0051_dndappointment_chats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajemovil',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='mensajemovil',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dndrsvp',
            name='type',
            field=models.CharField(choices=[('YES', 'Confirmo asistencia'), ('IF_NEED', 'Solo si es necesario'), ('NO', 'No puedo asistir')], max_length=30, verbose_name='Tipo de reserva'),
        ),
    ]
