# Generated by Django 2.2.24 on 2021-12-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0052_auto_20211228_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariojson',
            name='content',
            field=models.TextField(max_length=131072),
        ),
    ]
