# Generated by Django 2.2.24 on 2021-12-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0053_auto_20211228_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.TextField(max_length=4096, verbose_name='Subítulo'),
        ),
    ]
