# Generated by Django 3.2.18 on 2023-03-28 23:12

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0055_maparticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maparticle',
            name='geometries',
        ),
        migrations.RemoveField(
            model_name='maparticle',
            name='points',
        ),
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('body', martor.models.MartorField(blank=True, default='', verbose_name='Habilidades')),
                ('point', martor.models.MartorField()),
                ('map_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.maparticle')),
            ],
        ),
        migrations.CreateModel(
            name='MapGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('body', martor.models.MartorField(blank=True, default='', verbose_name='Habilidades')),
                ('geometry', martor.models.MartorField()),
                ('map_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.maparticle')),
            ],
        ),
    ]
