# Generated by Django 3.2.18 on 2023-03-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0057_auto_20230329_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='tipoMapa',
            field=models.CharField(choices=[('NO', 'Sin mapa'), ('GLOB', 'Mapa global'), ('DIG', 'Mapa de Digelia')], default='NO', max_length=8, verbose_name='Tipo de mapa'),
        ),
    ]
