# Generated by Django 3.2.18 on 2023-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0058_wikiarticle_tipomapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='redirect',
            field=models.CharField(default='', max_length=512),
        ),
    ]
