# Generated by Django 3.2.18 on 2023-11-01 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0060_alter_wikiarticle_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='belongsTo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.wikiarticle'),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='isCategory',
            field=models.BooleanField(default=False, verbose_name='Es categoría'),
        ),
    ]
