# Generated by Django 3.2.18 on 2023-11-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0062_auto_20231121_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndrsvp',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
