# Generated by Django 3.2.18 on 2023-11-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0063_alter_dndrsvp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndappointment',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
