# Generated by Django 3.2.18 on 2023-12-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0064_dndappointment_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticle',
            name='belongsTo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RolAndalucia.wikiarticle'),
        ),
    ]
