# Generated by Django 3.2.18 on 2023-12-13 16:26

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0065_alter_wikiarticle_belongsto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndappointment',
            name='body',
            field=martor.models.MartorField(blank=True, default='', verbose_name='Descripción de la sesión'),
        ),
    ]
