# Generated by Django 3.2.18 on 2025-01-15 20:10

from django.db import migrations, models
import django.db.models.deletion
import django_imgur.storage
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('RolAndalucia', '0066_dndappointment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', martor.models.MartorField(default='Lorem ipsum dolor sit amet', verbose_name='Texto')),
                ('description', martor.models.MartorField(default='Lorem ipsum dolor sit amet', verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='poll_pics')),
                ('public', models.BooleanField(default=False, verbose_name='Número de votos')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Identificador')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', martor.models.MartorField(default='Lorem ipsum dolor sit amet', verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='poll_pics')),
                ('allowedVotes', models.PositiveSmallIntegerField(default=1, verbose_name='Número de votos')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteNum', models.PositiveSmallIntegerField(verbose_name='Número de votos para esta pregunta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.question')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.voter')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', martor.models.MartorField(default='Lorem ipsum dolor sit amet', verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='poll_pics')),
                ('votes', models.PositiveSmallIntegerField(default=0, verbose_name='Número de votos')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RolAndalucia.question')),
            ],
        ),
    ]
